theme: jekyll-theme-minimal
title: Into the Male Gaze, a story of cinema representation
description: UtopianSky Website
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
